p="index.html"; s=open(p,encoding="utf-8").read()
# measure real damage dealt: every hp reduction on an enemy goes through dealt()
s=s.replace("function hurt(e,d,kx=0,ky=0,col){ d*=st().dmg;", "function dealt(d){ G.dmgLog.push([G.t,d]); }\nfunction hurt(e,d,kx=0,ky=0,col){ d*=st().dmg; dealt(d*(onMowed(e)?1.5:1));")
s=s.replace("if(d<bladeR+e.r*0.5){ e.hp-=bladeDps*dt*(onMowed(e)?1.5:1); e.hit=0.06;", "if(d<bladeR+e.r*0.5){ const bd=bladeDps*dt*(onMowed(e)?1.5:1); e.hp-=bd; dealt(bd); e.hit=0.06;")
s=s.replace("if(e.bleed>0){ e.bleed-=dt; e.hp-=6*dt*S.dmg;", "if(e.bleed>0){ e.bleed-=dt; e.hp-=6*dt*S.dmg; dealt(6*dt*S.dmg);")
s=s.replace("if(Math.hypot(e.x-w.x,e.y-w.y)<e.r+w.size){ e.hp-=w.dmg*dt*3;", "if(Math.hypot(e.x-w.x,e.y-w.y)<e.r+w.size){ e.hp-=w.dmg*dt*3; dealt(w.dmg*dt*3);")
s=s.replace("e.slow=0.6; e.slowf=j.slow; e.hp-=j.dmg*dt*3;", "e.slow=0.6; e.slowf=j.slow; e.hp-=j.dmg*dt*3; dealt(j.dmg*dt*3);")
s=s.replace("cd:{}, whackAng:0, sprAng:0, cam:{x:0,y:0}, camShake:0 };", "cd:{}, whackAng:0, sprAng:0, cam:{x:0,y:0}, camShake:0, dmgLog:[], dps:0 };")
# rolling 3 s window, updated in refreshSlots
s=s.replace("function refreshSlots(){ const p=G.p;", "function refreshSlots(){ const p=G.p; while(G.dmgLog.length&&G.t-G.dmgLog[0][0]>3) G.dmgLog.shift(); G.dps=G.dmgLog.reduce((a,x)=>a+x[1],0)/3;")
s=s.replace("MOWED ${G.mowedCount}<br><span style=", "MOWED ${G.mowedCount}<br>DPS <span style=\"color:#ffd54a\">${Math.round(G.dps)}</span><br><span style=")
s=s.replace('<div id="ver">v0.4.1</div>','<div id="ver">v0.4.2</div>')
open(p,"w",encoding="utf-8").write(s)
print("dps patched", s.count("dealt("))
