/**
 * Convert Grimoire (dnd-character) battle state → Iso3D map/units.
 * Presentation only — no rules.
 */

import { TERRAIN, createMap } from './map.js?v=0.6.14';
import { DIR_ORDER_8 } from './pathfinding.js?v=0.6.14';
import { MESH_DECOR_KINDS } from './terrainTextures.js?v=0.6.14';

/** Grimoire terrain key → Iso3D TERRAIN id */
export const GRIMOIRE_TERRAIN_MAP = {
  grass: TERRAIN.GRASS,
  stone: TERRAIN.CLIFF,
  wood: TERRAIN.DIRT,
  sand: TERRAIN.SAND,
  snow: TERRAIN.SAND,
  mud: TERRAIN.MUD,
  rubble: TERRAIN.DIRT,
  water: TERRAIN.WATER,
  brush: TERRAIN.GRASS,
  fog: TERRAIN.SAND,
  ice: TERRAIN.SAND,
  acid: TERRAIN.MUD,
  caltrops: TERRAIN.DIRT,
  lava: TERRAIN.CLIFF,
  wall: TERRAIN.CLIFF,       // full dungeon wall (tall)
  cave_wall: TERRAIN.CLIFF,  // natural cave rock (tall, distinct texture)
  low_wall: TERRAIN.CLIFF,   // outdoor parapet (shorter height below)
  window: TERRAIN.CLIFF,     // wall gap that lets light through (still solid, shorter)
  void: TERRAIN.VOID, // pit/chasm visual; walkability is Grimoire's job
  pit: TERRAIN.VOID,
  grease: TERRAIN.MUD,
  web: TERRAIN.SAND,
  floor: TERRAIN.GRASS,
};

/**
 * Canonical walk-sheet layout (4×4 tactics walk cycle).
 * Host samples: row = facing, col = walk frame.
 *
 *   cols: 4   → walk cycle (0 = idle, 1–3 = steps)
 *   rows: 4   → facing down, left, right, up (top → bottom)
 *   anchor: feet at bottom-center of each cell
 *   filter: nearest-neighbor
 *
 * Drop a PNG matching this grid and list it in DEFAULT_SPRITE_PATHS /
 * DEFAULT_SPRITE_DRAW — no renderer rewrite needed.
 */
export const SPRITE_SHEET_SPEC = {
  cols: 4,
  rows: 4,
  dirOrder: ['down', 'left', 'right', 'up'],
  /** Column used while standing still (gentle idle bob may still use 0–1). */
  idleCol: 0,
  /** Walk: cycle columns at ~2 frames per tile. */
  walkFpsHint: 8,
  /** Feet anchor (0–1 within frame). */
  anchor: { x: 0.5, y: 1.0 },
};

/**
 * Art pack for units — original chunky pixel sheets under sprites/hq/
 * (generated by tools/gen_pixel_sprites.py). No RPG Paper Maker assets.
 *
 * Walk/facing: 4×4 sheets (rows = down/left/right/up, cols = walk cycle).
 * See SPRITE_PIPELINE.md.
 */
export let SPRITE_PACK = 'hq';

/** All class keys with generated HQ walk sheets. */
export const HQ_CHARACTER_KEYS = new Set([
  'fighter', 'barbarian', 'paladin', 'ranger', 'rogue', 'monk', 'bard',
  'cleric', 'druid', 'wizard', 'sorcerer', 'warlock', 'artificer', 'human',
]);
/** All monster keys with generated HQ walk sheets. */
export const HQ_MONSTER_KEYS = new Set([
  'skeleton', 'zombie', 'spider', 'ogre', 'demon', 'slime', 'goblin',
  'ghost', 'wolf', 'orc', 'bear', 'snake', 'bat', 'rat', 'harpy', 'imp',
  'specter', 'mushroom', 'dog', 'cat', 'chicken', 'angel', 'mimic',
  'knight', 'villager', 'human',
]);

/** Relative path for a unit key under HQ pack root. */
export function spritePathFor(key, kind = 'character', pack = 'hq') {
  const folder = kind === 'monster' ? 'monsters' : 'characters';
  return `sprites/hq/${folder}/${key}.png`;
}

/**
 * Resolve sheet path. Missing keys fall back to fighter / goblin stand-ins.
 */
export function resolveSpritePath(key, kind = 'character') {
  const k = (key || '').toLowerCase();
  if (kind === 'monster') {
    if (HQ_MONSTER_KEYS.has(k)) return spritePathFor(k, 'monster', 'hq');
    return spritePathFor('goblin', 'monster', 'hq');
  }
  if (HQ_CHARACTER_KEYS.has(k)) return spritePathFor(k, 'character', 'hq');
  return spritePathFor('fighter', 'character', 'hq');
}

/** Cache-bust unit sheets (SW is cache-first for images — without ?v= old art sticks forever). */
const _SV = 'v133';
/** Grimoire class/monster sprite key → sheet path (all HQ). */
export const DEFAULT_SPRITE_PATHS = {
  fighter: `sprites/hq/characters/fighter.png?${_SV}`,
  barbarian: `sprites/hq/characters/barbarian.png?${_SV}`,
  paladin: `sprites/hq/characters/paladin.png?${_SV}`,
  ranger: `sprites/hq/characters/ranger.png?${_SV}`,
  rogue: `sprites/hq/characters/rogue.png?${_SV}`,
  monk: `sprites/hq/characters/monk.png?${_SV}`,
  bard: `sprites/hq/characters/bard.png?${_SV}`,
  cleric: `sprites/hq/characters/cleric.png?${_SV}`,
  druid: `sprites/hq/characters/druid.png?${_SV}`,
  wizard: `sprites/hq/characters/wizard.png?${_SV}`,
  sorcerer: `sprites/hq/characters/sorcerer.png?${_SV}`,
  warlock: `sprites/hq/characters/warlock.png?${_SV}`,
  artificer: `sprites/hq/characters/artificer.png?${_SV}`,
  skeleton: `sprites/hq/monsters/skeleton.png?${_SV}`,
  zombie: `sprites/hq/monsters/zombie.png?${_SV}`,
  spider: `sprites/hq/monsters/spider.png?${_SV}`,
  ogre: `sprites/hq/monsters/ogre.png?${_SV}`,
  demon: `sprites/hq/monsters/demon.png?${_SV}`,
  slime: `sprites/hq/monsters/slime.png?${_SV}`,
  goblin: `sprites/hq/monsters/goblin.png?${_SV}`,
  ghost: `sprites/hq/monsters/ghost.png?${_SV}`,
  wolf: `sprites/hq/monsters/wolf.png?${_SV}`,
  human: `sprites/hq/characters/human.png?${_SV}`,
  orc: `sprites/hq/monsters/orc.png?${_SV}`,
  bear: `sprites/hq/monsters/bear.png?${_SV}`,
  snake: `sprites/hq/monsters/snake.png?${_SV}`,
  bat: `sprites/hq/monsters/bat.png?${_SV}`,
  rat: `sprites/hq/monsters/rat.png?${_SV}`,
  harpy: `sprites/hq/monsters/harpy.png?${_SV}`,
  imp: `sprites/hq/monsters/imp.png?${_SV}`,
  specter: `sprites/hq/monsters/specter.png?${_SV}`,
  mushroom: `sprites/hq/monsters/mushroom.png?${_SV}`,
};

/**
 * Per-key draw + sheet layout overrides.
 * Always set cols/rows/dirOrder to match the PNG (see SPRITE_SHEET_SPEC).
 */
// Disgaea-style HQ: 128×128 frames, 4×4 walk sheets (512×512 PNG).
const _sheet4 = { targetFrameH: 96, pixelPerfect: true, cols: 4, rows: 4, dirOrder: SPRITE_SHEET_SPEC.dirOrder };
export const DEFAULT_SPRITE_DRAW = {
  fighter: { ..._sheet4, targetFrameH: 100 },
  paladin: { ..._sheet4, targetFrameH: 100 },
  barbarian: { ..._sheet4, targetFrameH: 104 },
  human: { ..._sheet4, targetFrameH: 96 },
  ranger: { ..._sheet4 },
  rogue: { ..._sheet4 },
  monk: { ..._sheet4 },
  bard: { ..._sheet4 },
  cleric: { ..._sheet4 },
  druid: { ..._sheet4 },
  wizard: { ..._sheet4, targetFrameH: 100 },
  sorcerer: { ..._sheet4 },
  warlock: { ..._sheet4 },
  artificer: { ..._sheet4 },
  goblin: { ..._sheet4, targetFrameH: 84 },
  skeleton: { ..._sheet4, targetFrameH: 92 },
  zombie: { ..._sheet4, targetFrameH: 92 },
  ogre: { ..._sheet4, targetFrameH: 108 },
  demon: { ..._sheet4, targetFrameH: 100 },
  slime: { ..._sheet4, targetFrameH: 72 },
  ghost: { ..._sheet4, targetFrameH: 88 },
  wolf: { ..._sheet4, targetFrameH: 80 },
  orc: { ..._sheet4, targetFrameH: 96 },
  bear: { ..._sheet4, targetFrameH: 92 },
  snake: { ..._sheet4, targetFrameH: 72 },
  bat: { ..._sheet4, targetFrameH: 72 },
  rat: { ..._sheet4, targetFrameH: 64 },
  harpy: { ..._sheet4, targetFrameH: 92 },
  imp: { ..._sheet4, targetFrameH: 80 },
  specter: { ..._sheet4, targetFrameH: 88 },
  mushroom: { ..._sheet4, targetFrameH: 76 },
  spider: { ..._sheet4, targetFrameH: 72 },
  // 8-direction sheets: 1 col, 8 rows.
  wiz: { targetFrameH: 96, pixelPerfect: true, cols: 1, rows: 8, dirOrder: DIR_ORDER_8 },
  wizard_purple: { targetFrameH: 96, pixelPerfect: true, cols: 1, rows: 8, dirOrder: DIR_ORDER_8 },
};

/**
 * Billboard decor ONLY — organic / flame props that read as sprites.
 * Doors, traps, grates, barrels, levers, etc. are pure meshes in buildMapMesh
 * (see MESH_DECOR_KINDS in terrainTextures.js) — never listed here.
 */
// Cache-bust after PixelLab full regen (lineless transparent props).
const _DV = 'v123';
// ONLY these plant billboards exist. No tree_dead / stump / snow variants as keys.
// torch ≠ campfire — wall torch is its own sprite (campfire is a ground fire).
export const DEFAULT_DECOR_PATHS = {
  tree: `sprites/hq/decor/tree.png?${_DV}`,
  tree2: `sprites/hq/decor/tree2.png?${_DV}`,
  bush: `sprites/hq/decor/bush.png?${_DV}`,
  bush2: `sprites/hq/decor/bush2.png?${_DV}`,
  bush3: `sprites/hq/decor/bush3.png?${_DV}`,
  rock: `sprites/hq/decor/rock.png?${_DV}`,
  crystal: `sprites/hq/decor/crystal.png?${_DV}`,
  ore: `sprites/hq/decor/ore.png?${_DV}`,
  torch: `sprites/hq/decor/torch.png?${_DV}`,
  torch_unlit: `sprites/hq/decor/torch_unlit.png?${_DV}`,
  campfire: `sprites/hq/decor/campfire.png?${_DV}`,
  bell: `sprites/hq/decor/bell.png?${_DV}`,
};

/**
 * Nuclear plant scrub: only `tree`, `tree2`, or `bush` / `bush2` / `bush3`.
 * Every former mini-tree kind is either a FULL tree or a bush.
 */
export function sanitizeMapDecor(decor) {
  if (!decor || typeof decor !== 'object') return {};
  const out = {};
  for (const [key, kind] of Object.entries(decor)) {
    if (!kind) continue;
    let k = String(kind).toLowerCase();
    // Explicit full trees only
    if (k === 'tree' || k === 'tree2') {
      out[key] = k;
      continue;
    }
    // Anything else with "tree" in the name → full oak (never a mini)
    if (k.includes('tree')) {
      out[key] = 'tree';
      continue;
    }
    // Bushes
    if (k.includes('bush')) {
      out[key] = k === 'bush2' || k === 'bush3' ? k : 'bush';
      continue;
    }
    // Former "small plant / stump / log" → bush only
    if (k === 'stump' || k === 'log' || k === 'mushroom' || k === 'flower') {
      out[key] = 'bush';
      continue;
    }
    // Pass through non-plant props if still allowed — billboard sprites (torch, crystal,
    // ...) AND mesh-only structure gadgets (door, trap, chest, lever, ...). Only the latter
    // check was missing here, so every door/trap/chest/lever/cauldron/drawbridge/grate/
    // barrel/chest map authors placed was silently dropped before it ever reached the
    // renderer — they showed up fine in the classic 2D view (a different code path) but
    // never appeared as 3D geometry in the WebGL view (live report: "we need 3d models for
    // the doors" — the models existed in renderer.js all along, this filter just never let
    // the decor entry through to trigger them).
    if (DEFAULT_DECOR_PATHS[k] || MESH_DECOR_KINDS.has(k)) out[key] = k;
    // else drop unknown plant-like junk
  }
  return out;
}

/** Keys allowed as camera-facing billboards. Structure gadgets are mesh-only. */
export const ISO3D_BILLBOARD_DECOR = new Set(Object.keys(DEFAULT_DECOR_PATHS));

/**
 * @param {{ cols:number, rows:number, tiles?:Record<string,string>, height?:Record<string,number>, decor?:Record<string,string> }} gMap
 */
export function grimoireMapToIso(gMap) {
  const cols = gMap.cols | 0;
  const rows = gMap.rows | 0;
  const map = createMap(cols, rows, 0, TERRAIN.GRASS);
  const tiles = gMap.tiles || {};
  const height = gMap.height || {};

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const key = `${c},${r}`;
      const cell = map.cells[r * cols + c];
      const tName = tiles[key] || 'grass';
      const type =
        GRIMOIRE_TERRAIN_MAP[tName] != null
          ? GRIMOIRE_TERRAIN_MAP[tName]
          : TERRAIN.GRASS;
      cell.type = type;
      // Keep Grimoire key so the renderer can pick the right terrain texture
      cell.gKey = tName;
      let h = height[key] != null ? Number(height[key]) : 0;
      if (!Number.isFinite(h)) h = 0;
      // Full walls = tall bulk (ceiling-height look). Low walls = short parapet.
      if (tName === 'wall' || tName === 'cave_wall') h = Math.max(h, 2);
      if (tName === 'low_wall' || tName === 'window') h = Math.max(h, 1);
      if (tName === 'water') h = 0;
      // Pits/voids are a real drop, not a flush-with-floor decal — live report: "the voids...
      // needs to actually lower elevation and have void at bottom." Fixed depth regardless of
      // authored height (a pit is always "the floor drops away here").
      if (tName === 'void' || tName === 'pit') h = -3;
      cell.h = Math.max(-4, Math.min(6, h | 0));
    }
  }

  return {
    map,
    decor: sanitizeMapDecor(gMap.decor || {}),
    light: gMap.light || null,
  };
}

const VALID_FACINGS = new Set([
  'down', 'left', 'right', 'up',
  'down-left', 'up-left', 'up-right', 'down-right',
]);

/**
 * Facing: Grimoire's 4-cardinal set, plus the 4 diagonals for 8-direction sprites
 * (facingFromStep in pathfinding.js emits these during diagonal movement).
 * @returns {'down'|'left'|'right'|'up'|'down-left'|'up-left'|'up-right'|'down-right'}
 */
export function normalizeFacing(f) {
  return VALID_FACINGS.has(f) ? f : 'down';
}

/**
 * @param {object} session - Grimoire session { map, players, monsters, order, turn, battle }
 * @param {{ assetBase?: string, spritePaths?: Record<string,string> }} [opts]
 */
export function grimoireSessionToView(session, opts = {}) {
  const assetBase = opts.assetBase || '';
  const paths = { ...DEFAULT_SPRITE_PATHS, ...(opts.spritePaths || {}) };
  const decorPaths = { ...DEFAULT_DECOR_PATHS, ...(opts.decorPaths || {}) };
  const { map, decor, light } = grimoireMapToIso(
    session.map || { cols: 10, rows: 8 },
  );
  if (light) map.light = light;
  else if (session.map && session.map.light) map.light = session.map.light;
  // Doors are built as real 3D wall-oriented quads in buildMapMesh (renderer.js), which
  // needs the raw col,row->kind decor map (not the billboard-only decorSprites list below)
  // to find door cells and detect their wall axis.
  map.decor = decor;

  const units = [];

  const drawOverrides = { ...DEFAULT_SPRITE_DRAW, ...(opts.spriteDraw || {}) };

  for (const pl of session.players || []) {
    if (pl.x == null || pl.y == null) continue;
    const cls = (pl.cls || (pl.c && pl.c.cls) || 'fighter').toLowerCase();
    // Explicit override (sprite-test.html's custom-key box) bypasses the HQ_CHARACTER_KEYS
    // whitelist entirely — lets you point at any file, even ones with no dedicated art yet,
    // instead of silently resolving to the fighter stand-in with no visible feedback.
    const explicitFile = opts.spritePaths && opts.spritePaths[cls];
    const spriteKey = explicitFile ? cls : (paths[cls] ? cls : 'fighter');
    const file = explicitFile || resolveSpritePath(spriteKey, 'character');
    // QB uses hpCur; also fall back to nested character sheet c.hp.cur
    const hp =
      pl.hpCur != null
        ? pl.hpCur
        : pl.hp != null
          ? pl.hp
          : pl.c && pl.c.hp
            ? pl.c.hp.cur
            : 1;
    const maxHp =
      pl.hpMax != null
        ? pl.hpMax
        : pl.maxHp != null
          ? pl.maxHp
          : pl.c && pl.c.hp
            ? pl.c.hp.max
            : hp || 1;
    units.push({
      id: `p:${pl.id || pl.cid || pl.name}`,
      source: 'player',
      raw: pl,
      col: pl.x | 0,
      row: pl.y | 0,
      team: 'player',
      label: pl.name || 'Player',
      hp,
      maxHp,
      // Treat missing HP as alive (don't hide the PC as a corpse)
      alive: hp == null || hp > 0,
      facing: normalizeFacing(pl.facing),
      spriteKey,
      spriteUrl: joinUrl(assetBase, file),
      spriteDraw: drawOverrides[spriteKey] || {
        targetFrameH: 56,
        pixelPerfect: true,
        cols: SPRITE_SHEET_SPEC.cols,
        rows: SPRITE_SHEET_SPEC.rows,
        dirOrder: SPRITE_SHEET_SPEC.dirOrder,
      },
      color: [0.25, 0.55, 0.95],
    });
  }

  for (const mo of session.monsters || []) {
    if (mo.x == null || mo.y == null) continue;
    const sk = (mo.sprite || 'goblin').toLowerCase();
    const spriteKey = paths[sk] ? sk : 'goblin';
    const file = resolveSpritePath(spriteKey, 'monster');
    const hp = mo.hp != null ? mo.hp : 0;
    units.push({
      id: `m:${mo.id}`,
      source: 'monster',
      raw: mo,
      col: mo.x | 0,
      row: mo.y | 0,
      team: 'enemy',
      label: mo.name || 'Monster',
      hp,
      maxHp: mo.max != null ? mo.max : mo.maxHp || hp || 1,
      alive: hp > 0,
      facing: normalizeFacing(mo.facing),
      spriteKey,
      spriteUrl: joinUrl(assetBase, file),
      spriteDraw: drawOverrides[spriteKey] || {
        targetFrameH: 50,
        pixelPerfect: true,
        cols: SPRITE_SHEET_SPEC.cols,
        rows: SPRITE_SHEET_SPEC.rows,
        dirOrder: SPRITE_SHEET_SPEC.dirOrder,
      },
      color: [0.85, 0.3, 0.25],
    });
  }

  // Decor billboards: trees/bushes/torches only. Structure gadgets (doors, traps, grates,
  // barrels, levers…) are real mesh in buildMapMesh — camera-facing sprites can't sit on
  // the floor or align to walls (door-rotation saga / purple Objects3D billboards).
  const decorSprites = [];
  // decor is already sanitizeMapDecor()'d — only tree/tree2/bush* + props remain
  for (const [key, kind] of Object.entries(decor || {})) {
    if (!kind || MESH_DECOR_KINDS.has(kind) || !ISO3D_BILLBOARD_DECOR.has(kind)) continue;
    const [cs, rs] = key.split(',');
    const col = Number(cs);
    const row = Number(rs);
    if (!Number.isFinite(col) || !Number.isFinite(row)) continue;
    const k = String(kind);
    const fileResolved = decorPaths[k];
    if (!fileResolved) continue;
    const isTree = k === 'tree' || k === 'tree2';
    const isBush = k.startsWith('bush');
    decorSprites.push({
      id: `d:${key}`,
      kind: k,
      col,
      row,
      spriteUrl: joinUrl(assetBase, fileResolved),
      // Host sizes from kind; these are only hints for 2D fallbacks.
      scale: isTree ? 3.2 : isBush ? 1.7 : 1.35,
      maxH: isTree ? 220 : isBush ? 60 : 42,
      // Hard flag so host never mis-classifies
      isFullTree: isTree,
    });
  }

  // Active turn unit id if order present
  let activeId = null;
  if (session.order && session.order.length) {
    const cur = session.order[session.turn || 0];
    if (cur) {
      activeId = cur.k === 'm' ? `m:${cur.id}` : `p:${cur.id}`;
    }
  }

  // Highlights from opts.reachCost / targets (optional, Grimoire mapGridHTML style)
  const highlights = buildHighlights(opts.highlights, map);
  // Lingering gas hazards (Cloudkill etc., see index.html's SPELL_GAS/tickGasHazards) —
  // unlike Grease/Web these don't repaint session.map.tiles at all (real bug hit live: a
  // gas cloud looked like plain floor in the WebGL view despite still dealing damage every
  // round — the classic 2D view already got a CSS overlay for this, this is the same fix
  // for Iso3D). Folded into `highlights.gas` (not a separate top-level view field) so it
  // rides the exact same "project each cell, draw a colored quad every frame" overlay
  // path host.js already has for move/dash/attack-range highlighting — no new mesh, no
  // new fx primitive, just one more entry in that layer list.
  if (session.hazards && session.hazards.length) {
    const gasCells = new Set();
    for (const hz of session.hazards) {
      if (!hz.gas) continue;
      for (const c of hz.cells) gasCells.add(`${c.x},${c.y}`);
    }
    if (gasCells.size) highlights.gas = gasCells;
  }

  return {
    map,
    decor,
    decorSprites,
    units,
    activeId,
    highlights,
    dynamicLights: session.lights || [],
  };
}

function buildHighlights(h, map) {
  if (!h) return {};
  let move = null;
  let dash = null;
  let jump = null;
  let climb = null;
  if (h.reachCost) {
    move = new Set();
    dash = new Set();
    jump = new Set();
    climb = new Set();
    const normal = h.reachNormal != null ? h.reachNormal : 1e9;
    for (const key of Object.keys(h.reachCost)) {
      const fc = h.reachCost[key];
      if (!(fc > 0)) continue;
      if (fc > normal) dash.add(key);
      else move.add(key);
      const rm = h.reachMeta && h.reachMeta[key];
      if (rm && rm.jump) jump.add(key);
      if (rm && rm.climb) climb.add(key);
    }
  }
  if (h.move) move = h.move;
  if (h.dash) dash = h.dash;
  if (h.jump) jump = h.jump;
  if (h.climb) climb = h.climb;
  const attack = h.attackTiles
    ? h.attackTiles instanceof Set
      ? h.attackTiles
      : new Set(h.attackTiles)
    : h.attack || null;
  // Range / AoE / pre-roll badges must pass through (syncIso3DHost builds these)
  const attackRange = h.attackRange
    ? h.attackRange instanceof Set
      ? h.attackRange
      : new Set(h.attackRange)
    : null;
  const attackRangeMax = h.attackRangeMax
    ? h.attackRangeMax instanceof Set
      ? h.attackRangeMax
      : new Set(h.attackRangeMax)
    : null;
  const blast = h.blast
    ? h.blast instanceof Set
      ? h.blast
      : new Set(h.blast)
    : null;
  // Valid attack targets (monster/player ids or "x,y" keys)
  let targetIds = null;
  if (h.targetIds) {
    targetIds = h.targetIds instanceof Set ? h.targetIds : new Set(h.targetIds);
  } else if (h.targets) {
    targetIds = new Set(
      (Array.isArray(h.targets) ? h.targets : [...h.targets]).map(String),
    );
  }
  return {
    move,
    dash,
    jump,
    climb,
    attack,
    attackRange,
    attackRangeMax,
    blast,
    aoeR: h.aoeR != null ? h.aoeR : null,
    blastLocked: !!h.blastLocked,
    aoePreview: h.aoePreview || null,
    targetIds,
    targetInfo: h.targetInfo || null,
    selected: h.selected || null,
    hover: h.hover || null,
  };
}

function joinUrl(base, path) {
  if (!path) return path;
  if (/^https?:\/\//i.test(path) || path.startsWith('/')) return path;
  if (!base) return path;
  return base.replace(/\/?$/, '/') + path.replace(/^\//, '');
}

/**
 * Iso grid (col,row) uses same axes as Grimoire (x,y).
 * Rotation 0–3 matches Grimoire mapRotation for camera yaw only.
 */
export function rotationToYaw(rot) {
  // Grimoire rot 0 = default; each step +90°
  // Our camera: rot 0 ≈ looking along -Z-ish; use π/4 base + k*π/2
  const r = ((rot % 4) + 4) % 4;
  return Math.PI / 4 + (r * Math.PI) / 2;
}

/** Demo session shaped like Grimoire (for bridge.html, no presets needed). */
export function makeDemoGrimoireSession() {
  const cols = 12;
  const rows = 10;
  const tiles = {};
  const height = {};
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < cols; x++) {
      tiles[`${x},${y}`] = 'grass';
    }
  }
  // water pond
  for (let y = 1; y <= 3; y++) for (let x = 1; x <= 3; x++) tiles[`${x},${y}`] = 'water';
  // dirt path
  for (let y = 0; y < rows; y++) tiles[`5,${y}`] = 'mud';
  // cliff ridge
  for (let y = 3; y <= 7; y++) {
    tiles[`8,${y}`] = 'wall';
    height[`8,${y}`] = 1;
    tiles[`9,${y}`] = 'stone';
    height[`9,${y}`] = 2;
  }
  // sand shore
  for (let x = 0; x < cols; x++) tiles[`${x},${rows - 1}`] = 'sand';

  return {
    map: { cols, rows, tiles, height, decor: { '3,5': 'bush', '6,2': 'tree' } },
    players: [
      {
        id: 'p1',
        name: 'Aldric',
        cls: 'Fighter',
        x: 2,
        y: 7,
        hpCur: 12,
        hpMax: 14,
        facing: 'up',
      },
      {
        id: 'p2',
        name: 'Nyx',
        cls: 'Rogue',
        x: 3,
        y: 8,
        hpCur: 9,
        hpMax: 10,
        facing: 'right',
      },
    ],
    monsters: [
      {
        id: 'm1',
        name: 'Goblin A',
        sprite: 'goblin',
        x: 7,
        y: 2,
        hp: 7,
        max: 7,
        facing: 'down',
      },
      {
        id: 'm2',
        name: 'Skeleton',
        sprite: 'skeleton',
        x: 10,
        y: 4,
        hp: 13,
        max: 13,
        facing: 'left',
      },
      {
        id: 'm3',
        name: 'Wolf',
        sprite: 'wolf',
        x: 6,
        y: 4,
        hp: 11,
        max: 11,
        facing: 'down',
      },
    ],
    order: [
      { k: 'p', id: 'p1', name: 'Aldric' },
      { k: 'm', id: 'm1', name: 'Goblin A' },
      { k: 'p', id: 'p2', name: 'Nyx' },
      { k: 'm', id: 'm2', name: 'Skeleton' },
      { k: 'm', id: 'm3', name: 'Wolf' },
    ],
    turn: 0,
    battle: { active: true, round: 1 },
  };
}

